#if !canImport(ObjectiveC)
  import XCTest

  extension BushelKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BushelKitTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(BushelKitTests.__allTests__BushelKitTests)
    ]
  }
#endif
