stages:
  - build
  - lint
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    
cache:
  - key: 
      files:
        - Package.resolved
    paths:
      - Packages/BushelKit/.build
      - ~/.swiftpm
  - key:
      files: 
        - Mintfile
    paths:
      - .mint

.lint_template: &lint_template
  stage: lint
  tags:
    - macos
  script:
    - ./Scripts/package.sh
    - git diff --exit-code
    - xcodes select 15.1
    - brew install mint
    - LINT_MODE=$LINT_MODE ./Scripts/lint.sh    

build spm macos:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
  tags:
      - macos
  script: 
    - xcodes select 15.1
    - cd Packages/BushelKit
    - swift build
    - xcodebuild test -scheme BushelKit-Package -sdk iphonesimulator17.2 -destination "OS=17.0.1,name=iPhone 14"

build spm linux 5.9.0-nightly:
  stage: build
  only:
    - merge_requests
    - main
    - /^v\d+.\d+.\d+(-\w+\.\d+)?$/
  image: swiftlang/swift:nightly-5.9-jammy
  script:
    - cd Packages/BushelKit
    - swift build
    - swift test
build spm linux 5.9.0:
  stage: build
  only:
    - merge_requests
    - main
    - /^v\d+.\d+.\d+(-\w+\.\d+)?$/
  image: swift:5.9.0-jammy
  script:
    - cd Packages/BushelKit
    - swift build
    - swift test
  
lint lenient:
  only:
    - merge_requests
  <<: *lint_template

lint strict:
  only:
    - /^v\d+\.\d+\.\d+(-\w+\.\d+)?$/
    - /STRICT/
  variables:
   LINT_MODE: "STRICT"
  <<: *lint_template  

deploy:
  stage: deploy
  cache:
    key:
      files:
        - Gemfile.lock
    paths:
      - vendor/ruby
  tags:
    - macos  
  only:
    - main
    - /^v\d+.\d+.\d+(-\w+\.\d+)?$/
    - /ARCHIVE/
  script:
    - if [ "$CI_COMMIT_REF_NAME" = "main" ]; then LANE_NAME="beta"; else LANE_NAME="archive"; fi
    - rbenv rehash
    - rbenv exec bundle install
    - xcodes select 15.0.1
    - LINT_MODE=NONE xcodegen
    - git remote set-url --push origin git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
    - rbenv exec bundle exec fastlane $LANE_NAME
