stages:
  - build
  - lint
  - deploy
  
cache:
  key: 
    files:
      - Package.resolved
  paths:
    - Packages/BushelKit/.build
    - ~/.swiftpm


.build_spm_template: &build_spm_template
  stage: build
  script:
    - cd Packages/BushelKit
    - swift build
    - swift test

.lint_template: &lint_template
  stage: lint
  tags:
    - macos
  script:
    - LINT_MODE=$LINT_MODE ./scripts/lint.sh    

build spm macos:
  only:
    - branches
  tags:
      - macos
  <<: *build_spm_template

build spm linux 5.6.2:
  only:
    - merge_requests
  image: swift:5.6.2
  <<: *build_spm_template

build spm linux 5.7.0:
  only:
    - merge_requests
  image: swift:5.7-jammy
  <<: *build_spm_template

build spm linux 5.7.1:
  only:
    - merge_requests
    - main
    - /^v\/*/
  image: swiftlang/swift:nightly-5.7-jammy
  <<: *build_spm_template
  
lint lenient:
  only:
    - merge_requests
  <<: *lint_template

lint strict:
  only:
    - main
    - /^v\/*/
  variables:
    LINT_MODE: "STRICT"
  <<: *lint_template  

deploy:
  stage: deploy
  cache:
    key:
      files:
        - Gemfile.lock
    paths:
      - vendor/ruby
  tags:
    - macos  
  only:
    - main
  script:
    - rbenv rehash
    - rbenv exec bundle install
    # - speculid process Assets/Speculid/AppIcon.speculid
    # - speculid process Assets/Speculid/Logo.speculid
    - LINT_MODE=NONE xcodegen
    - git remote set-url --push origin git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
    - rbenv exec bundle exec fastlane beta
