stages:
  - build
  - lint
  - deploy
  
cache:
  - key: 
      files:
        - Package.resolved
    paths:
      - Packages/BushelKit/.build
      - ~/.swiftpm
  - key:
      files: 
        - Mintfile
    paths:
      - .mint

.lint_template: &lint_template
  stage: lint
  tags:
    - macos
  script:
    - ./Scripts/package.sh
    - git diff --exit-code --quiet
    - xcodes select 15
    - brew install mint
    - LINT_MODE=$LINT_MODE ./Scripts/lint.sh    

build spm macos:
  stage: build
  only:
    - branches
  tags:
      - macos
  script: 
    - xcodes select 15 
    - cd Packages/BushelKit
    - swift build

build spm linux 5.9.0:
  stage: build
  only:
    - merge_requests
    - main
    - /^v\/*/
  image: swiftlang/swift:nightly-5.9-jammy
  script:
    - cd Packages/BushelKit
    - swift build
    - swift test
  
lint lenient:
  only:
    - merge_requests
  <<: *lint_template

lint strict:
  only:
    - main
    - /^v\/*/
  #variables:
  #  LINT_MODE: "STRICT"
  <<: *lint_template  

deploy:
  stage: deploy
  cache:
    key:
      files:
        - Gemfile.lock
    paths:
      - vendor/ruby
  tags:
    - macos  
  only:
    - main
  script:
    - rbenv rehash
    - rbenv exec bundle install
    - xcodes select 15
    - LINT_MODE=NONE xcodegen
    - git remote set-url --push origin git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
    - rbenv exec bundle exec fastlane beta
