name: Bushel
options:
  bundleIdPrefix: com.brightdigit
  deploymentTarget:
    macOS: 12.0
settings:
  DEVELOPMENT_TEAM: MLT7M394S7
  CODE_SIGN_IDENTITY: "Apple Development"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: 33
  bundleIdPrefix: com.brightdigit
  PRODUCT_NAME: Bushel
  DEAD_CODE_STRIPING: true
  LINT_MODE: ${LINT_MODE}
packages:
  BushelUI:
    path: ./Packages/BushelKit
targets:
  Bushel:
    type: application
    platform: macOS
    scheme: {}
    dependencies:
      - package: BushelUI
      - sdk: Virtualization.framework
    info:
      path: Support/macOS/Info.plist
      properties:
        CFBundlePackageType: APPL
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSHumanReadableCopyright: Copyright (c) 2022 BrightDigit
        LSApplicationCategoryType: public.app-category.developer-tools
        ATSApplicationFontsPath: .
        CFBundleDocumentTypes:
          - {CFBundleTypeName: 'macOS Restore Image', CFBundleTypeRole: Viewer, LSHandlerRank: Alternate, LSItemContentTypes: [com.apple.iphone.ipsw, com.apple.itunes.ipsw]}
          - {CFBundleTypeName: 'Bushel Virtual Machine', CFBundleTypeRole: Editor, LSHandlerRank: Owner, LSItemContentTypes: [com.brightdigit.bushel-vm], NSUbiquitousDocumentUserActivityType: $(PRODUCT_BUNDLE_IDENTIFIER).bushel-vm}
          - {CFBundleTypeName: 'Bushel Image Library', CFBundleTypeRole: Editor, LSHandlerRank: Owner, LSItemContentTypes: [com.brightdigit.bushel-rilib], NSUbiquitousDocumentUserActivityType: $(PRODUCT_BUNDLE_IDENTIFIER).bushel-rilib}
        CFBundleURLTypes:
          - {CFBundleURLSchemes: [bushel]}
        UIAppFonts:
          - Raleway-VariableFont_wght.ttf
          - Raleway-Italic-VariableFont_wght.ttf
        UTExportedTypeDeclarations:
          - {UTTypeConformsTo: [com.apple.package], UTTypeDescription: 'Bushel Virtual Machine', UTTypeIcons: {UTTypeIconBackgroundName: Machine-Fill, UTTypeIconBadgeName: Machine-Icon, UTTypeIconText: machine}, UTTypeIdentifier: com.brightdigit.bushel-vm, UTTypeTagSpecification: {public.filename-extension: [bshvm]}}
          - {UTTypeConformsTo: [com.apple.package], UTTypeDescription: 'Bushel Image Library', UTTypeIcons: {UTTypeIconBackgroundName: ImageLibrary-Fill, UTTypeIconBadgeName: ImageLibrary-Icon, UTTypeIconText: images}, UTTypeIdentifier: com.brightdigit.bushel-rilib, UTTypeTagSpecification: {public.filename-extension: [bshrilib]}}
        UTImportedTypeDeclarations:
          - {UTTypeConformsTo: [''], UTTypeIdentifier: com.apple.iphone.ipsw, UTTypeTagSpecification: {public.filename-extension: [ipsw]}}
          - {UTTypeConformsTo: [''], UTTypeIdentifier: com.apple.itunes.ipsw, UTTypeTagSpecification: {public.filename-extension: [ipsw]}}
    sources:
      - path: "Support/macOS"
        name: macOS
        group: Support
      - path: "Sources/macOS"
        name: macOS
        group: Sources
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundleIdPrefix}.Bushel
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.Bushel macos
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.Bushel macos
    entitlements:
      path: Support/macOS/macOS.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
        com.apple.security.virtualization: true
        com.apple.vm.networking: true
        com.apple.security.application-groups:
          - group.com.brightdigit.Bushel
    postBuildScripts:
      - path: scripts/lint.sh
        name: Lint
        basedOnDependencyAnalysis: false
  Bushel-UITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: "Tests/macOS/UI"
        name: UI
        group: Tests/macOS
    scheme:
      testTargets:
        - Bushel-UITests
    settings:
      TEST_TARGET_NAME: Bushel
      GENERATE_INFOPLIST_FILE: true
