name: Bushel
options:
  preGenCommand: ./Scripts/packages.sh
  bundleIdPrefix: com.brightdigit
  developmentLanguage: en
  deploymentTarget:
    macOS: 14.0
settings:
  DEVELOPMENT_TEAM: MLT7M394S7
  CODE_SIGN_IDENTITY: "Apple Development"
  MARKETING_VERSION: "2.0.0"
  CURRENT_PROJECT_VERSION: 127
  bundleIdPrefix: com.brightdigit
  PRODUCT_NAME: Bushel
  DEAD_CODE_STRIPING: true
  LINT_MODE: ${LINT_MODE}
  SWIFT_STRICT_CONCURRENCY: complete
  SWIFT_VERSION: 6
  _EXPERIMENTAL_SWIFT_EXPLICIT_MODULES: true
  ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: false
packages:
  BushelApp:
    path: ./Packages/BushelApp
  RadiantKit:
    path: ./Packages/RadiantKit
targetTemplates:
  Application:
    type: application
    platform: macOS
    scheme:
      environmentVariables:
        DISABLE_ASSERTION_FAILURE_FOR_ERROR: ${DISABLE_ASSERTION_FAILURE_FOR_ERROR}
    dependencies:
      - package: BushelApp
        product: Bushel${packageName}App
      - sdk: Virtualization.framework
    info:
      path: Support/macOS/Info.plist
      properties:
        CFBundlePackageType: APPL
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSHumanReadableCopyright: Copyright (c) 2024 BrightDigit
        LSApplicationCategoryType: public.app-category.developer-tools
        BrightDigitStoreGroupIDList:
          - 21016280
        BrightDigitURLDirectory:
          privacyPolicy: https://getbushel.app/privacy-policy
          termsOfUse: https://getbushel.app/terms-of-use
          support: https://getbushel.app/support
          company: https://brightdigit.com
          discourse: https://discourse.getbushel.app
          contactMailTo: mailto:leo@brightdigit.com?subject=About%20Bushel...
        ATSApplicationFontsPath: .
        CFBundleDocumentTypes:
          - {CFBundleTypeName: 'macOS Restore Image', CFBundleTypeRole: Viewer, LSHandlerRank: Alternate, LSItemContentTypes: [com.apple.iphone.ipsw, com.apple.itunes.ipsw]}
          - {CFBundleTypeName: 'Bushel Virtual Machine', CFBundleTypeRole: Editor, LSHandlerRank: Owner, LSItemContentTypes: [com.brightdigit.bushel-vm], NSUbiquitousDocumentUserActivityType: $(PRODUCT_BUNDLE_IDENTIFIER).bushel-vm}
          - {CFBundleTypeName: 'Bushel Image Library', CFBundleTypeRole: Editor, LSHandlerRank: Owner, LSItemContentTypes: [com.brightdigit.bushel-rilib], NSUbiquitousDocumentUserActivityType: $(PRODUCT_BUNDLE_IDENTIFIER).bushel-rilib}
        CFBundleURLTypes:
          - {CFBundleURLSchemes: [bushel]}
        UTExportedTypeDeclarations:
          - {UTTypeConformsTo: [com.apple.package], UTTypeDescription: 'Bushel Virtual Machine', UTTypeIcons: {UTTypeIconBackgroundName: Machine-Fill, UTTypeIconBadgeName: Machine-Icon, UTTypeIconText: machine}, UTTypeIdentifier: com.brightdigit.bushel-vm, UTTypeTagSpecification: {public.filename-extension: [bshvm]}}
          - {UTTypeConformsTo: [com.apple.package], UTTypeDescription: 'Bushel Image Library', UTTypeIcons: {UTTypeIconBackgroundName: ImageLibrary-Fill, UTTypeIconBadgeName: ImageLibrary-Icon, UTTypeIconText: images}, UTTypeIdentifier: com.brightdigit.bushel-rilib, UTTypeTagSpecification: {public.filename-extension: [bshrilib]}}
        UTImportedTypeDeclarations:
          - {UTTypeConformsTo: [''], UTTypeIdentifier: com.apple.iphone.ipsw, UTTypeTagSpecification: {public.filename-extension: [ipsw]}}
          - {UTTypeConformsTo: [''], UTTypeIdentifier: com.apple.itunes.ipsw, UTTypeTagSpecification: {public.filename-extension: [ipsw]}}
        BrightDigitXPCService: ${bundleIdPrefix}.BushelXPC
        Sentry:
          DSN: https://0702167a293f6722329ad00476520db4@o919385.ingest.us.sentry.io/4507307052105728
        WishKit:
          APIKey: E97E7359-8F7A-43DD-B8FC-D447B4A46DD8
        BrightDigitPrereleaseInfo:
          Label: beta
          Base: 109
    sources:
      - path: "Support/macOS"
        name: macOS
        group: Support
        optional: true
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundleIdPrefix}.Bushel${productName}
    entitlements:
      path: Support/macOS/macOS.entitlements
      properties:
        com.apple.security.files.bookmarks.app-scope: true
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
        com.apple.security.virtualization: true
        com.apple.vm.networking: true
        com.apple.security.application-groups:
          - group.com.brightdigit.Bushel
    postBuildScripts:
      - path: scripts/lint.sh
        name: Lint
        basedOnDependencyAnalysis: false
  Microapp:
    templates:
      - Application
    templateAttributes:
      packageName: ${target_name}
      productName: ${target_name}
    sources:
      - path: "Apps/${target_name}"
        group: Apps
targets:
  BushelXPC:
    platform: macOS
    type: xpc-service
    settings:
      base:
        PRODUCT_NAME: BushelXPC
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.BushelXPC macos
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.BushelXPC macos
    sources:
      - path: "Sources/XPC"
        name: XPC
        group: Sources
    info:
      path: Support/XPC/Info.plist
      properties:
        BrightDigitXPCService: ${bundleIdPrefix}.BushelXPC
        XPCService:
          ServiceType: Application
    dependencies:
      - package: BushelApp
        product: BushelService
      - sdk: Virtualization.framework
    entitlements:
      path: Support/XPC/macOS.entitlements
      properties:
        com.apple.security.files.bookmarks.app-scope: true
        com.apple.security.app-sandbox: true
        com.apple.security.network.server: true
        com.apple.security.virtualization: true
        com.apple.vm.networking: true
        com.apple.security.application-groups:
          - group.com.brightdigit.Bushel
  Bushel:
    templates:
      - Application
    templateAttributes:
      packageName:
      productName:
    dependencies:
      - target: BushelXPC
    sources:
      - path: "Sources/macOS"
        name: macOS
        group: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundleIdPrefix}.Bushel
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.Bushel macos
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.Bushel macos
  Bushel-UITests:
    type: bundle.ui-testing
    platform: macOS
    scheme:
      testTargets:
        - Bushel-UITests
    dependencies:
      - package: BushelApp
        product: BushelUITests
    settings:
      TEST_TARGET_NAME: Bushel
      GENERATE_INFOPLIST_FILE: true
