# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV['SPACESHIP_CONNECT_API_KEY_ID'],
      issuer_id: ENV['SPACESHIP_CONNECT_API_ISSUER_ID'],
      key_content: ENV['SPACESHIP_CONNECT_API_KEY_CONTENT']
    )
    match(type: "appstore", additional_cert_types: "mac_installer_distribution", readonly: is_ci)
    build_app(
      output_directory: "public",
      build_path: "public",
      scheme: "Bushel",
      export_options: {
        provisioningProfiles: { 
          "com.brightdigit.Bushel" => "match AppStore com.brightdigit.Bushel macos"
        },
        installer_cert_name: "Mac Installer Distribution: BRIGHT DIGIT LLC (MLT7M394S7)",
      }
    )
    #upload_to_testflight
  end
end
