included: # paths to include during linting. `--path` is ignored if present.
- Sources
# Customize specific rules
missing:
  severity: error

partial:
  severity: warning

unused:
  severity: warning

missing_comment:
  severity: warning