name: DocC
on:
  push:
    branches-ignore:
      - '*WIP'
  # workflow_run:
  #   workflows: ["BushelKit"]
  #   types: 
  #     - completed
         
jobs:
  build-docc:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    container:
      image: swift:6.0-noble
      volumes:
        - ${{ github.workspace }}:/workspace
    steps:
      - uses: actions/checkout@v4
      - name: Cache swift package modules
        id: cache-spm-linux
        uses: actions/cache@v4
        env:
          cache-name: cache-spm
        with:
          path: .build
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.swift-version }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.swift-version }}-
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Build DocC
        run: swift package generate-documentation --platform "name=macos,version=15.1" --transform-for-static-hosting --hosting-base-path "swift-docc" --disable-indexing --enable-experimental-combined-documentation
      - name: Package DocArchive
        working-directory: .build/plugins/Swift-DocC/outputs
        run: tar -cf BushelKit.doccarchive.tar BushelKit.doccarchive
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          path: /workspace/.build/plugins/Swift-DocC/outputs/BushelKit.doccarchive.tar
          retention-days: 1
